{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "import dash\n",
    "from dash.dependencies import Output, Input\n",
    "import dash_core_components as dcc\n",
    "import dash_html_components as html\n",
    "import plotly\n",
    "import random\n",
    "import plotly.graph_objs as go\n",
    "from collections import deque"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "X = deque(maxlen=20)\n",
    "X.append(1)\n",
    "Y = deque(maxlen=20)\n",
    "Y.append(1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [],
   "source": [
    "# app = dash.Dash(__name__)\n",
    "# app.layout = html.Div(\n",
    "#     [\n",
    "#         dcc.Graph(id = 'live-graph',animate = True),\n",
    "#         dcc.Interval(\n",
    "#         id = 'graph-update',\n",
    "#         interval = 1*1000\n",
    "#         ),\n",
    "#     ]\n",
    "# )\n",
    "\n",
    "# @app.callback(Output('live-graph','figure'),\n",
    "#             [Input('graph-update', 'n_intervals')])\n",
    "\n",
    "# def update_graph_scatter():\n",
    "#     X.append(X[-1]+1)\n",
    "#     Y.append(Y[-1]+Y[-1]*random.uniform(-0.1,0.1))\n",
    "    \n",
    "#     data = plotly.graph_objs.Scatter(\n",
    "#         x = list(X),\n",
    "#         y = list(Y),\n",
    "#         name = 'Scatter',\n",
    "#         mode = 'lines+markers'\n",
    "#         )\n",
    "    \n",
    "#     return {'data': [data],'layout' : go.Layout(xaxis=dict(range=[min(X),max(X)]),\n",
    "#                                                 yaxis=dict(range=[min(Y),max(Y)]),)}\n",
    "    \n",
    "\n",
    "# if __name__ == '__main__':\n",
    "#     app.run_server()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: This is a development server. Do not use it in a production deployment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\dash\\dash.py\", line 1032, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\dash\\dash.py\", line 967, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "TypeError: update_graph_scatter() takes 0 positional arguments but 1 was given\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\dash\\dash.py\", line 1032, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\dash\\dash.py\", line 967, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "TypeError: update_graph_scatter() takes 0 positional arguments but 1 was given\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\dash\\dash.py\", line 1032, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\dash\\dash.py\", line 967, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "TypeError: update_graph_scatter() takes 0 positional arguments but 1 was given\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\dash\\dash.py\", line 1032, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\dash\\dash.py\", line 967, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "TypeError: update_graph_scatter() takes 0 positional arguments but 1 was given\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\dash\\dash.py\", line 1032, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\dash\\dash.py\", line 967, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "TypeError: update_graph_scatter() takes 0 positional arguments but 1 was given\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\dash\\dash.py\", line 1032, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\dash\\dash.py\", line 967, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "TypeError: update_graph_scatter() takes 0 positional arguments but 1 was given\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\dash\\dash.py\", line 1032, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\dash\\dash.py\", line 967, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "TypeError: update_graph_scatter() takes 0 positional arguments but 1 was given\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\dash\\dash.py\", line 1032, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\dash\\dash.py\", line 967, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "TypeError: update_graph_scatter() takes 0 positional arguments but 1 was given\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\dash\\dash.py\", line 1032, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\dash\\dash.py\", line 967, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "TypeError: update_graph_scatter() takes 0 positional arguments but 1 was given\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\dash\\dash.py\", line 1032, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\dash\\dash.py\", line 967, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "TypeError: update_graph_scatter() takes 0 positional arguments but 1 was given\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\dash\\dash.py\", line 1032, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\dash\\dash.py\", line 967, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "TypeError: update_graph_scatter() takes 0 positional arguments but 1 was given\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [12/Jun/2020 13:57:50] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\dash\\dash.py\", line 1032, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\dash\\dash.py\", line 967, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "TypeError: update_graph_scatter() takes 0 positional arguments but 1 was given\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\dash\\dash.py\", line 1032, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\dash\\dash.py\", line 967, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "TypeError: update_graph_scatter() takes 0 positional arguments but 1 was given\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\dash\\dash.py\", line 1032, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"c:\\users\\shaurya.vardhan\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\dash\\dash.py\", line 967, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "TypeError: update_graph_scatter() takes 0 positional arguments but 1 was given\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [12/Jun/2020 13:57:50] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    }
   ],
   "source": [
    "import dash\n",
    "from dash.dependencies import Output, Input\n",
    "import dash_core_components as dcc\n",
    "import dash_html_components as html\n",
    "import plotly\n",
    "import random\n",
    "import plotly.graph_objs as go\n",
    "from collections import deque\n",
    "\n",
    "X = deque(maxlen=20)\n",
    "X.append(1)\n",
    "Y = deque(maxlen=20)\n",
    "Y.append(1)\n",
    "\n",
    "\n",
    "app = dash.Dash(__name__)\n",
    "app.layout = html.Div(\n",
    "    [\n",
    "        dcc.Graph(id='live-graph', animate=True),\n",
    "        dcc.Interval(\n",
    "            id='graph-update',\n",
    "            interval=1*100\n",
    "        ),\n",
    "    ]\n",
    ")\n",
    "\n",
    "@app.callback(Output('live-graph', 'figure'),\n",
    "              [Input('graph-update', 'n_intervals')])\n",
    "def update_graph_scatter():\n",
    "    X.append(X[-1]+1)\n",
    "    Y.append(Y[-1]+Y[-1]*random.uniform(-0.1,0.1))\n",
    "\n",
    "    data = plotly.graph_objs.Scatter(\n",
    "            x=list(X),\n",
    "            y=list(Y),\n",
    "            name='Scatter',\n",
    "            mode= 'lines+markers'\n",
    "            )\n",
    "\n",
    "    return {'data': [data],'layout' : go.Layout(xaxis=dict(range=[min(X),max(X)]),\n",
    "                                                yaxis=dict(range=[min(Y),max(Y)]),)}\n",
    "\n",
    "\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run_server()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3rc1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
